# Generated by Django 5.1.6 on 2025-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("marketplace", models.CharField(max_length=50)),
                ("id_flux", models.CharField(max_length=50)),
                (
                    "order_status_marketplace",
                    models.CharField(blank=True, max_length=50),
                ),
                ("order_status_lengow", models.CharField(blank=True, max_length=50)),
                (
                    "order_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("order_mrid", models.CharField(max_length=50, unique=True)),
                ("order_refid", models.CharField(max_length=50, unique=True)),
                ("order_external_id", models.CharField(blank=True, max_length=50)),
                ("order_purchase_date", models.DateField(null=True)),
                ("order_purchase_time", models.TimeField(null=True)),
                ("order_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "order_shipping",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "order_commission",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "order_processing_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("order_currency", models.CharField(max_length=10)),
                ("payment_checkout", models.CharField(blank=True, max_length=50)),
                ("payment_status", models.CharField(blank=True, max_length=50)),
                ("payment_type", models.CharField(blank=True, max_length=50)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_time", models.TimeField(blank=True, null=True)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("invoice_url", models.URLField(blank=True)),
                ("billing_society", models.CharField(blank=True, max_length=100)),
                ("billing_civility", models.CharField(blank=True, max_length=50)),
                ("billing_lastname", models.CharField(max_length=100)),
                ("billing_firstname", models.CharField(blank=True, max_length=100)),
                ("billing_email", models.EmailField(max_length=254)),
                ("billing_address", models.CharField(blank=True, max_length=255)),
                ("billing_address_2", models.CharField(blank=True, max_length=255)),
                (
                    "billing_address_complement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("billing_zipcode", models.CharField(max_length=20)),
                ("billing_city", models.CharField(max_length=100)),
                ("billing_country", models.CharField(max_length=100)),
                ("billing_country_iso", models.CharField(blank=True, max_length=10)),
                ("billing_phone_home", models.CharField(blank=True, max_length=20)),
                ("billing_phone_office", models.CharField(blank=True, max_length=20)),
                ("billing_phone_mobile", models.CharField(blank=True, max_length=20)),
                ("billing_full_address", models.TextField()),
                ("delivery_society", models.CharField(blank=True, max_length=100)),
                ("delivery_civility", models.CharField(blank=True, max_length=50)),
                ("delivery_lastname", models.CharField(blank=True, max_length=100)),
                ("delivery_firstname", models.CharField(blank=True, max_length=100)),
                ("delivery_email", models.EmailField(blank=True, max_length=254)),
                ("delivery_address", models.CharField(blank=True, max_length=255)),
                ("delivery_address_2", models.CharField(blank=True, max_length=255)),
                (
                    "delivery_address_complement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("delivery_zipcode", models.CharField(max_length=20)),
                ("delivery_city", models.CharField(max_length=100)),
                ("delivery_country", models.CharField(max_length=100)),
                ("delivery_country_iso", models.CharField(blank=True, max_length=10)),
                ("delivery_phone_home", models.CharField(blank=True, max_length=20)),
                ("delivery_phone_office", models.CharField(blank=True, max_length=20)),
                ("delivery_phone_mobile", models.CharField(blank=True, max_length=20)),
                ("delivery_full_address", models.TextField()),
                ("tracking_method", models.CharField(blank=True, max_length=50)),
                ("tracking_carrier", models.CharField(blank=True, max_length=50)),
                ("tracking_number", models.CharField(blank=True, max_length=50)),
                ("tracking_url", models.URLField(blank=True)),
                ("tracking_shipped_date", models.DateTimeField(blank=True, null=True)),
                ("tracking_relay", models.CharField(blank=True, max_length=50)),
                (
                    "tracking_delivering_by_marketplace",
                    models.BooleanField(default=False),
                ),
                (
                    "tracking_parcel_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("order_comments", models.TextField(blank=True)),
                ("customer_id", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
