# Generated by Django 5.1.6 on 2025-02-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_id_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_ip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
