# Generated by Django 5.1.6 on 2025-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_country_iso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
