# Generated by Django 5.1.6 on 2025-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_billing_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_country_iso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
