# Generated by Django 5.1.6 on 2025-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_delivery_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_purchase_time',
            field=models.TimeField(null=True),
        ),
    ]
